services:
  mongodb:
    container_name: techie_mongo_db
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - spring-boot-network
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456

  mongo-express:
    container_name: techie_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - spring-boot-network
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false

  db_mysql:
    image: mysql:latest
    container_name: techie_mysql
    ports:
      - "3307:3306"
    networks:
      - spring-boot-network
    environment:
      - MYSQL_DATABASE=order-service
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
#      - .data:/var/lib/mysql

volumes:
  mongo:

networks:
  spring-boot-network:
    driver: bridge