spring:
  application:
    name: inventory-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/inventory-service
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 0

#server:
#  port: 8083
